server:
  port: 8082
spring:
  application:
    name: csv_reader
  cloud:
    config:
      name: csv_reader
      uri: http://127.0.0.1:7777/
  config:
    import: optional:configserver:http://127.0.0.1:7777
  profiles:
    active: dev
  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
      defaultZone: http://localhost:8761/eureka