server:
  port: 8085
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: csv-reader
          uri: lb://csv-reader
          predicates:
            - Path=/api/person/**
        - id: person_consumer_service
          uri: lb://person-consumer-service
          predicates:
            - Path=/api/persons/**