server:
  port: 8085
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
        routes:
          - id: csv_reader
            uri: http://localhost:8082
            predicates:
              - Path=/api/person/**

          - id: person_consumer_service
            uri: http://localhost:8084
            predicates:
              - Path=/api/persons/**
